<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Subdistrict;

class SubdistrictSeeder extends Seeder
{
    public function run(): void
    {
        $subdistricts = [
            ['id' => 1, 'subdistrict_name' => 'Pandansari', 'subdistrict_code' => 'KD01', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'subdistrict_name' => 'Bangunharjo', 'subdistrict_code' => 'KD02', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'subdistrict_name' => 'Kauman', 'subdistrict_code' => 'KD03', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'subdistrict_name' => 'Purwodinatan', 'subdistrict_code' => 'KD04', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'subdistrict_name' => 'Pindrikan Lor', 'subdistrict_code' => 'KD05', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'subdistrict_name' => 'Kranggan', 'subdistrict_code' => 'KD06', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'subdistrict_name' => 'Kembangsari', 'subdistrict_code' => 'KD07', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'subdistrict_name' => 'Pindrikan Kidul', 'subdistrict_code' => 'KD08', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'subdistrict_name' => 'Sekayu', 'subdistrict_code' => 'KD09', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'subdistrict_name' => 'Miroto', 'subdistrict_code' => 'KD10', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'subdistrict_name' => 'Tlogosari Wetan', 'subdistrict_code' => 'KD100', 'district_code' => 'KC10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 12, 'subdistrict_name' => 'Tlogomulyo', 'subdistrict_code' => 'KD101', 'district_code' => 'KC10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 13, 'subdistrict_name' => 'Palebon', 'subdistrict_code' => 'KD102', 'district_code' => 'KC10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 14, 'subdistrict_name' => 'Pedurungan Tengah', 'subdistrict_code' => 'KD103', 'district_code' => 'KC10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 15, 'subdistrict_name' => 'Pedurungan Lor', 'subdistrict_code' => 'KD104', 'district_code' => 'KC10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 16, 'subdistrict_name' => 'Plamongansari', 'subdistrict_code' => 'KD105', 'district_code' => 'KC10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 17, 'subdistrict_name' => 'Pedurungan Kidul', 'subdistrict_code' => 'KD106', 'district_code' => 'KC10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 18, 'subdistrict_name' => 'Penggaron Kidul', 'subdistrict_code' => 'KD107', 'district_code' => 'KC10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 19, 'subdistrict_name' => 'Kedungmundu', 'subdistrict_code' => 'KD108', 'district_code' => 'KC11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 20, 'subdistrict_name' => 'Tandang', 'subdistrict_code' => 'KD109', 'district_code' => 'KC11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 21, 'subdistrict_name' => 'Brumbungan', 'subdistrict_code' => 'KD11', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 22, 'subdistrict_name' => 'Jangli', 'subdistrict_code' => 'KD110', 'district_code' => 'KC11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 23, 'subdistrict_name' => 'Sendangguwo', 'subdistrict_code' => 'KD111', 'district_code' => 'KC11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 24, 'subdistrict_name' => 'Sendangmulyo', 'subdistrict_code' => 'KD112', 'district_code' => 'KC11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 25, 'subdistrict_name' => 'Sambiroto', 'subdistrict_code' => 'KD113', 'district_code' => 'KC11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 26, 'subdistrict_name' => 'Mangunharjo (Tembalang)', 'subdistrict_code' => 'KD114', 'district_code' => 'KC11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 27, 'subdistrict_name' => 'Rowosari', 'subdistrict_code' => 'KD115', 'district_code' => 'KC11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 28, 'subdistrict_name' => 'Meteseh', 'subdistrict_code' => 'KD116', 'district_code' => 'KC11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 29, 'subdistrict_name' => 'Kramas', 'subdistrict_code' => 'KD117', 'district_code' => 'KC11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 30, 'subdistrict_name' => 'Tembalang', 'subdistrict_code' => 'KD118', 'district_code' => 'KC11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 31, 'subdistrict_name' => 'Bulusan', 'subdistrict_code' => 'KD119', 'district_code' => 'KC11', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 32, 'subdistrict_name' => 'Jagalan', 'subdistrict_code' => 'KD12', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 33, 'subdistrict_name' => 'Ngesrep', 'subdistrict_code' => 'KD120', 'district_code' => 'KC12', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 34, 'subdistrict_name' => 'Sumurboto', 'subdistrict_code' => 'KD121', 'district_code' => 'KC12', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 35, 'subdistrict_name' => 'Tinjomoyo', 'subdistrict_code' => 'KD122', 'district_code' => 'KC12', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 36, 'subdistrict_name' => 'Padangsari', 'subdistrict_code' => 'KD123', 'district_code' => 'KC12', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 37, 'subdistrict_name' => 'Pedalangan', 'subdistrict_code' => 'KD124', 'district_code' => 'KC12', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 38, 'subdistrict_name' => 'Jabungan', 'subdistrict_code' => 'KD125', 'district_code' => 'KC12', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 39, 'subdistrict_name' => 'Srondol Kulon', 'subdistrict_code' => 'KD126', 'district_code' => 'KC12', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 40, 'subdistrict_name' => 'Srondol Wetan', 'subdistrict_code' => 'KD127', 'district_code' => 'KC12', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 41, 'subdistrict_name' => 'Banyumanik', 'subdistrict_code' => 'KD128', 'district_code' => 'KC12', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 42, 'subdistrict_name' => 'Pudakpayung', 'subdistrict_code' => 'KD129', 'district_code' => 'KC12', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 43, 'subdistrict_name' => 'Gabahan', 'subdistrict_code' => 'KD13', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 44, 'subdistrict_name' => 'Gedawang', 'subdistrict_code' => 'KD130', 'district_code' => 'KC12', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 45, 'subdistrict_name' => 'Gunungpati', 'subdistrict_code' => 'KD131', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 46, 'subdistrict_name' => 'Plalangan', 'subdistrict_code' => 'KD132', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 47, 'subdistrict_name' => 'Pakintelan', 'subdistrict_code' => 'KD133', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 48, 'subdistrict_name' => 'Nongkosawit', 'subdistrict_code' => 'KD134', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 49, 'subdistrict_name' => 'Cepoko', 'subdistrict_code' => 'KD135', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 50, 'subdistrict_name' => 'Jatirejo', 'subdistrict_code' => 'KD136', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 51, 'subdistrict_name' => 'Sumurrejo', 'subdistrict_code' => 'KD137', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 52, 'subdistrict_name' => 'Mangunsari', 'subdistrict_code' => 'KD138', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 53, 'subdistrict_name' => 'Pongangan', 'subdistrict_code' => 'KD139', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 54, 'subdistrict_name' => 'Karang Kidul', 'subdistrict_code' => 'KD14', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 55, 'subdistrict_name' => 'Kandri', 'subdistrict_code' => 'KD140', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 56, 'subdistrict_name' => 'Sadeng', 'subdistrict_code' => 'KD141', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 57, 'subdistrict_name' => 'Sekaran', 'subdistrict_code' => 'KD142', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 58, 'subdistrict_name' => 'Sukorejo', 'subdistrict_code' => 'KD143', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 59, 'subdistrict_name' => 'Kalisegoro', 'subdistrict_code' => 'KD144', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 60, 'subdistrict_name' => 'Patemon', 'subdistrict_code' => 'KD145', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 61, 'subdistrict_name' => 'Ngijo', 'subdistrict_code' => 'KD146', 'district_code' => 'KC13', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 62, 'subdistrict_name' => 'Mijen', 'subdistrict_code' => 'KD147', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 63, 'subdistrict_name' => 'Ngadirgo', 'subdistrict_code' => 'KD148', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 64, 'subdistrict_name' => 'Kedungpane', 'subdistrict_code' => 'KD149', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 65, 'subdistrict_name' => 'Pekunden', 'subdistrict_code' => 'KD15', 'district_code' => 'KC01', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 66, 'subdistrict_name' => 'Cangkiran', 'subdistrict_code' => 'KD150', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 67, 'subdistrict_name' => 'Tambangan', 'subdistrict_code' => 'KD151', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 68, 'subdistrict_name' => 'Jatisari', 'subdistrict_code' => 'KD152', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 69, 'subdistrict_name' => 'Wonolopo', 'subdistrict_code' => 'KD153', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 70, 'subdistrict_name' => 'Wonoplumbon', 'subdistrict_code' => 'KD154', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 71, 'subdistrict_name' => 'Pesantren', 'subdistrict_code' => 'KD155', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 72, 'subdistrict_name' => 'Jatibarang', 'subdistrict_code' => 'KD156', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 73, 'subdistrict_name' => 'Karangmalang', 'subdistrict_code' => 'KD157', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 74, 'subdistrict_name' => 'Bubakan', 'subdistrict_code' => 'KD158', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 75, 'subdistrict_name' => 'Polaman', 'subdistrict_code' => 'KD159', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 76, 'subdistrict_name' => 'Bandarharjo', 'subdistrict_code' => 'KD16', 'district_code' => 'KC02', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 77, 'subdistrict_name' => 'Purwosari (Mijen)', 'subdistrict_code' => 'KD160', 'district_code' => 'KC14', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 78, 'subdistrict_name' => 'Tambakaji', 'subdistrict_code' => 'KD161', 'district_code' => 'KC15', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 79, 'subdistrict_name' => 'Wonosari', 'subdistrict_code' => 'KD162', 'district_code' => 'KC15', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 80, 'subdistrict_name' => 'Purwoyoso', 'subdistrict_code' => 'KD163', 'district_code' => 'KC15', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 81, 'subdistrict_name' => 'Kalipancur', 'subdistrict_code' => 'KD164', 'district_code' => 'KC15', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 82, 'subdistrict_name' => 'Ngaliyan', 'subdistrict_code' => 'KD165', 'district_code' => 'KC15', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 83, 'subdistrict_name' => 'Bambankerep', 'subdistrict_code' => 'KD166', 'district_code' => 'KC15', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 84, 'subdistrict_name' => 'Wates', 'subdistrict_code' => 'KD167', 'district_code' => 'KC15', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 85, 'subdistrict_name' => 'Beringin', 'subdistrict_code' => 'KD168', 'district_code' => 'KC15', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 86, 'subdistrict_name' => 'Gondoriyo', 'subdistrict_code' => 'KD169', 'district_code' => 'KC15', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 87, 'subdistrict_name' => 'Tanjung mas', 'subdistrict_code' => 'KD17', 'district_code' => 'KC02', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 88, 'subdistrict_name' => 'Podorejo', 'subdistrict_code' => 'KD170', 'district_code' => 'KC15', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 89, 'subdistrict_name' => 'Mangkang Kulon', 'subdistrict_code' => 'KD171', 'district_code' => 'KC16', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 90, 'subdistrict_name' => 'Mangkang Wetan', 'subdistrict_code' => 'KD172', 'district_code' => 'KC16', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 91, 'subdistrict_name' => 'Mangunharjo (Tugu)', 'subdistrict_code' => 'KD173', 'district_code' => 'KC16', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 92, 'subdistrict_name' => 'Tugurejo', 'subdistrict_code' => 'KD174', 'district_code' => 'KC16', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 93, 'subdistrict_name' => 'Jerakah', 'subdistrict_code' => 'KD175', 'district_code' => 'KC16', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 94, 'subdistrict_name' => 'Karanganyar', 'subdistrict_code' => 'KD176', 'district_code' => 'KC16', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 95, 'subdistrict_name' => 'Randugarut', 'subdistrict_code' => 'KD177', 'district_code' => 'KC16', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 96, 'subdistrict_name' => 'Kuningan', 'subdistrict_code' => 'KD18', 'district_code' => 'KC02', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 97, 'subdistrict_name' => 'Dadapsari', 'subdistrict_code' => 'KD19', 'district_code' => 'KC02', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 98, 'subdistrict_name' => 'Bulu Lor', 'subdistrict_code' => 'KD20', 'district_code' => 'KC02', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 99, 'subdistrict_name' => 'Panggung Kidul', 'subdistrict_code' => 'KD21', 'district_code' => 'KC02', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 100, 'subdistrict_name' => 'Purwosari (Semarang Utara)', 'subdistrict_code' => 'KD22', 'district_code' => 'KC02', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 101, 'subdistrict_name' => 'Plombokan', 'subdistrict_code' => 'KD23', 'district_code' => 'KC02', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 102, 'subdistrict_name' => 'Panggung Lor', 'subdistrict_code' => 'KD24', 'district_code' => 'KC02', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 103, 'subdistrict_name' => 'Karangtempel', 'subdistrict_code' => 'KD25', 'district_code' => 'KC03', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 104, 'subdistrict_name' => 'Karangturi', 'subdistrict_code' => 'KD26', 'district_code' => 'KC03', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 105, 'subdistrict_name' => 'Rejosari', 'subdistrict_code' => 'KD27', 'district_code' => 'KC03', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 106, 'subdistrict_name' => 'Sarirejo', 'subdistrict_code' => 'KD28', 'district_code' => 'KC03', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 107, 'subdistrict_name' => 'Bugangan', 'subdistrict_code' => 'KD29', 'district_code' => 'KC03', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 108, 'subdistrict_name' => 'Kebonagung', 'subdistrict_code' => 'KD30', 'district_code' => 'KC03', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 109, 'subdistrict_name' => 'Mlatiharjo', 'subdistrict_code' => 'KD31', 'district_code' => 'KC03', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 110, 'subdistrict_name' => 'Rejomulyo', 'subdistrict_code' => 'KD32', 'district_code' => 'KC03', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 111, 'subdistrict_name' => 'Kemijen', 'subdistrict_code' => 'KD33', 'district_code' => 'KC03', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 112, 'subdistrict_name' => 'Mlatibaru', 'subdistrict_code' => 'KD34', 'district_code' => 'KC03', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 113, 'subdistrict_name' => 'Barusari', 'subdistrict_code' => 'KD35', 'district_code' => 'KC04', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 114, 'subdistrict_name' => 'Bulustalan', 'subdistrict_code' => 'KD36', 'district_code' => 'KC04', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 115, 'subdistrict_name' => 'Pleburan', 'subdistrict_code' => 'KD37', 'district_code' => 'KC04', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 116, 'subdistrict_name' => 'Wonodri', 'subdistrict_code' => 'KD38', 'district_code' => 'KC04', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 117, 'subdistrict_name' => 'Mugasari', 'subdistrict_code' => 'KD39', 'district_code' => 'KC04', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 118, 'subdistrict_name' => 'Randusari', 'subdistrict_code' => 'KD40', 'district_code' => 'KC04', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 119, 'subdistrict_name' => 'Lamper Tengah', 'subdistrict_code' => 'KD41', 'district_code' => 'KC04', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 120, 'subdistrict_name' => 'Lamper Kidul', 'subdistrict_code' => 'KD42', 'district_code' => 'KC04', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 121, 'subdistrict_name' => 'Lamper Lor', 'subdistrict_code' => 'KD43', 'district_code' => 'KC04', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 122, 'subdistrict_name' => 'Peterongan', 'subdistrict_code' => 'KD44', 'district_code' => 'KC04', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 123, 'subdistrict_name' => 'Karangayu', 'subdistrict_code' => 'KD45', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 124, 'subdistrict_name' => 'Salamanmloyo', 'subdistrict_code' => 'KD46', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 125, 'subdistrict_name' => 'Cabean', 'subdistrict_code' => 'KD47', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 126, 'subdistrict_name' => 'Bojongsalaman', 'subdistrict_code' => 'KD48', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 127, 'subdistrict_name' => 'Kalibanteng Kulon', 'subdistrict_code' => 'KD49', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 128, 'subdistrict_name' => 'Kalibanteng Kidul', 'subdistrict_code' => 'KD50', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 129, 'subdistrict_name' => 'Tambakharjo', 'subdistrict_code' => 'KD51', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 130, 'subdistrict_name' => 'Gisikdrono', 'subdistrict_code' => 'KD52', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 131, 'subdistrict_name' => 'Manyaran', 'subdistrict_code' => 'KD53', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 132, 'subdistrict_name' => 'Krapyak', 'subdistrict_code' => 'KD54', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 133, 'subdistrict_name' => 'Kembangarum', 'subdistrict_code' => 'KD55', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 134, 'subdistrict_name' => 'Krobokan', 'subdistrict_code' => 'KD56', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 135, 'subdistrict_name' => 'TawangMas', 'subdistrict_code' => 'KD57', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 136, 'subdistrict_name' => 'Tawangsari', 'subdistrict_code' => 'KD58', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 137, 'subdistrict_name' => 'Ngemplak Simongan', 'subdistrict_code' => 'KD59', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 138, 'subdistrict_name' => 'Bongsari', 'subdistrict_code' => 'KD60', 'district_code' => 'KC05', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 139, 'subdistrict_name' => 'Gayamsari', 'subdistrict_code' => 'KD61', 'district_code' => 'KC06', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 140, 'subdistrict_name' => 'Siwalan', 'subdistrict_code' => 'KD62', 'district_code' => 'KC06', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 141, 'subdistrict_name' => 'Tambakrejo', 'subdistrict_code' => 'KD63', 'district_code' => 'KC06', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 142, 'subdistrict_name' => 'Kaligawe', 'subdistrict_code' => 'KD64', 'district_code' => 'KC06', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 143, 'subdistrict_name' => 'Sawah Besar', 'subdistrict_code' => 'KD65', 'district_code' => 'KC06', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 144, 'subdistrict_name' => 'Sambirejo', 'subdistrict_code' => 'KD66', 'district_code' => 'KC06', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 145, 'subdistrict_name' => 'Pandean Lamper', 'subdistrict_code' => 'KD67', 'district_code' => 'KC06', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 146, 'subdistrict_name' => 'Karanganyar Gunung', 'subdistrict_code' => 'KD68', 'district_code' => 'KC07', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 147, 'subdistrict_name' => 'Jomblang', 'subdistrict_code' => 'KD69', 'district_code' => 'KC07', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 148, 'subdistrict_name' => 'Jatingaleh', 'subdistrict_code' => 'KD70', 'district_code' => 'KC07', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 149, 'subdistrict_name' => 'Wonotinggal', 'subdistrict_code' => 'KD71', 'district_code' => 'KC07', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 150, 'subdistrict_name' => 'Candi', 'subdistrict_code' => 'KD72', 'district_code' => 'KC07', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 151, 'subdistrict_name' => 'Kaliwiru', 'subdistrict_code' => 'KD73', 'district_code' => 'KC07', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 152, 'subdistrict_name' => 'Tegalsari', 'subdistrict_code' => 'KD74', 'district_code' => 'KC07', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 153, 'subdistrict_name' => 'Sampangan', 'subdistrict_code' => 'KD75', 'district_code' => 'KC08', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 154, 'subdistrict_name' => 'Bendan Ngisor', 'subdistrict_code' => 'KD76', 'district_code' => 'KC08', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 155, 'subdistrict_name' => 'Bendan Dhuwur', 'subdistrict_code' => 'KD77', 'district_code' => 'KC08', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 156, 'subdistrict_name' => 'Gajahmungkur', 'subdistrict_code' => 'KD78', 'district_code' => 'KC08', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 157, 'subdistrict_name' => 'Lempongsari', 'subdistrict_code' => 'KD79', 'district_code' => 'KC08', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 158, 'subdistrict_name' => 'Petompon', 'subdistrict_code' => 'KD80', 'district_code' => 'KC08', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 159, 'subdistrict_name' => 'Bendungan', 'subdistrict_code' => 'KD81', 'district_code' => 'KC08', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 160, 'subdistrict_name' => 'Karangrejo', 'subdistrict_code' => 'KD82', 'district_code' => 'KC08', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 161, 'subdistrict_name' => 'Genuksari', 'subdistrict_code' => 'KD83', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 162, 'subdistrict_name' => 'Banjardowo', 'subdistrict_code' => 'KD84', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 163, 'subdistrict_name' => 'Trimulyo', 'subdistrict_code' => 'KD85', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 164, 'subdistrict_name' => 'Muktiharjo Lor', 'subdistrict_code' => 'KD86', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 165, 'subdistrict_name' => 'Terboyo Kulon', 'subdistrict_code' => 'KD87', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 166, 'subdistrict_name' => 'Terboyo Wetan', 'subdistrict_code' => 'KD88', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 167, 'subdistrict_name' => 'Gebangsari', 'subdistrict_code' => 'KD89', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 168, 'subdistrict_name' => 'Bangetayu Kulon', 'subdistrict_code' => 'KD90', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 169, 'subdistrict_name' => 'Bangetayu Wetan', 'subdistrict_code' => 'KD91', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 170, 'subdistrict_name' => 'Sembungharjo', 'subdistrict_code' => 'KD92', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 171, 'subdistrict_name' => 'Penggaron Lor', 'subdistrict_code' => 'KD93', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 172, 'subdistrict_name' => 'Kudu', 'subdistrict_code' => 'KD94', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 173, 'subdistrict_name' => 'Karangroto', 'subdistrict_code' => 'KD95', 'district_code' => 'KC09', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 174, 'subdistrict_name' => 'Tlogosari Kulon', 'subdistrict_code' => 'KD96', 'district_code' => 'KC10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 175, 'subdistrict_name' => 'Gemah', 'subdistrict_code' => 'KD97', 'district_code' => 'KC10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 176, 'subdistrict_name' => 'Kalicari', 'subdistrict_code' => 'KD98', 'district_code' => 'KC10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 177, 'subdistrict_name' => 'Muktiharjo Kidul', 'subdistrict_code' => 'KD99', 'district_code' => 'KC10', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 178, 'subdistrict_name' => 'Luar Kota', 'subdistrict_code' => 'xxx', 'district_code' => 'xxx', 'created_at' => now(), 'updated_at' => now()],
        ];

        foreach ($subdistricts as $subdistrictData) {
            Subdistrict::firstOrCreate(['subdistrict_code' => $subdistrictData['subdistrict_code']], $subdistrictData);
        }
    }
}
